### ISSUE TITLE
@-ms-viewport { width: device-width }

### ISSUE THREAD

**Issue by paulirish** [h5bp/html5-boilerplate#1047]
Might be too early for this but.. 

``` css
@-ms-viewport { width: device-width; }
```

.. looks necessary, according to http://hammerspace.co.uk/2012/04/responsive-design-in-internet-explorer-10-windows-8
