### ISSUE TITLE
".ir" img replacement leaves a blank space in Android 2.2, Webkit 3.1

### ISSUE THREAD

**Issue by ArnaudDelafosse** [h5bp/html5-boilerplate#1092]
Nicolas Gallagher's new IR technique ( http://tinyurl.com/7havl66 )

``` css
.ir {
    font: 0/0 a;
    text-shadow: none;
    color: transparent;
}
```

...leaves a blank space where the text should appear.
