### ISSUE TITLE
vector icons embedded in a webfont

### ISSUE THREAD

**Issue by gtraxx** [h5bp/html5-boilerplate#1212]
Hello, I am using html5boilerplate to write my new software available in a few months.

I currently test technique typicons to have icons of good quality and the ability to use CSS to change them. (http://typicons.com/)

What do you think of this technique can be improved to integrate partially in html5boileplate?

Once my new beta software I will share (open source) :)

Example with typicons for info:

``` css
@font-face {
    font-family: 'Typicons';
    src: url('fonts/typicons-regular-webfont.eot');
    src: url('fonts/typicons-regular-webfont.eot?#iefix') format('embedded-opentype'),
        url('fonts/typicons-regular-webfont.woff') format('woff'),
        url('fonts/typicons-regular-webfont.ttf') format('truetype'),
        url('fonts/typicons-regular-webfont.svg#TypiconsRegular') format('svg');
    font-weight: normal;
    font-style: normal;
}

.typicn {
    font-family: "Typicons", sans-serif;
    /* Reduce blur on icons in chrome, opera, safari and ios. */
    /* This is hacky & bad. Maybe possible for firefox, not sure yet. */
    -webkit-font-smoothing: antialiased;    -o-transform: scale(1); 
}

.location:before {content: "A";}
```

Best regards
