### ISSUE TITLE
Print media queries incompatible with ant-build-script

### ISSUE THREAD

**Issue by ademey** [h5bp/html5-boilerplate#1315]
The example print media queries are not compatible with the css compressor in ant-build-script. Setting a pixel ratio as a fraction instead of decimal will cause the css to become malformed. For example:

``` css
  @media print,
         (-o-min-device-pixel-ratio: 5/4),
         (-webkit-min-device-pixel-ratio: 1.25),
         (min-resolution: 120dpi) {
      /* Style adjustments for high resolution devices */
  }

  @media print {
      * {
          background: transparent !important;
          color: #000 !important; /* Black prints faster: h5bp.com/s */
          box-shadow: none !important;
          text-shadow: none !important;
      }
  }
```

becomes:

``` css
@media print,(-o-min-device-pixel-ratio:5/@media print{*{background:transparent!important;color:#000!important;box-shadow:none!important;text-shadow:none!important}}
```

Changing (-o-min-device-pixel-ratio: 5/4) to 1.25 seems to fix the problem.
