### ISSUE TITLE
Remove background colour from ::selection altogether

### ISSUE THREAD

**Issue by chee** [h5bp/html5-boilerplate#1391]
#407 #610 & #969 focused on getting rid of hotPink/#fe57a1 as the default text-selection background colour, but shouldn't we get rid of a default text-selection background colour altogether?

When the blue isn't exactly the same blue as the operating system/browser defaults, you end up with two different shades of blue when you select between paragraphs. Also, if one has set ones operating-system-level default text-selection background colour, or DTSBC, to something other than blue, one gets two different colours when selecting a whole page.

Shouldn't we just use:

``` css
::-moz-selection {                                                                                   
  text-shadow: none;                                                                          
}                                                                                                      

::selection {                                                                                  
  text-shadow: none;                                                                         
}
```
