### ISSUE TITLE
Remove `span`

### ISSUE THREAD

**Issue by zlatanvasovic** [h5bp/html5-boilerplate#1454]
[Question about Skype Click to Call](https://github.com/h5bp/html5-boilerplate/blob/v5.0.0/doc/faq.md#how-do-i-prevent-phone-numbers-looking-twice-as-large-and-having-a-skype-highlight) has unneeded CSS.

Code:

``` css
span.skype_pnh_container {
    display: none !important;
}

span.skype_pnh_print_container {
    display: inline !important;
}
```

`span` isn't needed (class is enought) because of `!important` is used, right?
