### ISSUE TITLE
Collision between main.css and normilize.css

### ISSUE THREAD

**Issue by ArmorDarks** [h5bp/html5-boilerplate#1662]
Hi

May be I'm wrong, but it seems that main.css and normilie.css have opposite rules:

``` css
/* main.css */

audio,
canvas,
iframe,
img,
svg,
video {
    vertical-align: middle;
}
```

``` css
/* normilize.css */

audio,
canvas,
progress,
video {
  display: inline-block; /* 1 */
  vertical-align: baseline; /* 2 */
}
```

Notice that first block defines for `audio`, `canvas` and `video` `vertical-align: middle;`, while block from normalize.css defines for them `vertical-align: baseline;` instead
