### ISSUE TITLE
fixing media query scrollbar issue?

### ISSUE THREAD

**Issue by MattDiMu** [h5bp/html5-boilerplate#1693]
According to the [w3c](http://www.w3.org/TR/css3-mediaqueries/#width) the width of scrollbar is part of a media query definition. As the scrollbar-width of browsers varies quite a lot (up to 21px afaik), a media query does NOT tell a developer how much space is available.

So using something like
```css
@media (min-width: 360px) {
  .element {
  width: 340px;
  margin-left: auto;
  margin-right: auto;
  }
}
```
may or may not cause a scrollbar, which may be really annoying when developing/testing.

What are the reasons for not including a hack like 
````css
html {
  height: 100%;
  overflow: hidden;
}

body {
  height: 100%;
  position: relative;
  overflow-y: scroll;
  /*-webkit-overflow-scrolling:touch;*/
}
````

From what I've researched, giving the body 100% may cause layout changes/problems (in combination with background-images), but I didn't find any real argument against it.
