### ISSUE TITLE
Print style for code block

### ISSUE THREAD

**Issue by akhyarrh** [h5bp/html5-boilerplate#1742]
![2015-07-30_15-07-00](https://cloud.githubusercontent.com/assets/10618799/10395868/dd085232-6ed1-11e5-9e51-ce91d6e515f2.png)

On some sites, code block are not wrapped when printed. This is bad as I'm one of the people who love printing some articles to read later or archived it.

Currently I use stylish to inject style below to all site.

```css
@media print {
  pre {
    white-space: pre-wrap !important;
  }
}
```

I think its good to add that style or maybe someone have another idea ?
