### ISSUE TITLE
Improve ::selection documentation

### ISSUE THREAD

**Issue by maoberlehner** [h5bp/html5-boilerplate#1953]
The comment `These selection rule sets have to be separate.` (https://github.com/maoberlehner/html5-boilerplate/blob/abc64efcb71847049620bf8ae78f3cd5ce26bf5e/src/css/main.css#L21) does not make any sense anymore in the source file after the changes made in c7057bef0c432c245d678d5ea4cf16526619cafb

I realize that it makes sense in the `dist/css/main.css` file tough. In my opinion the comment should not be in the source file and is also not necessary in the dist file. I'm happy to commit a pull request if the people are agreeing. Otherwise, how could this be solved so that the comment is added on build time?

**Comment by roblarsen** [comment]
Pretend (because it's true!) that I don't remember the original context for the comment and need it explained to me because I'm time-crunched right now

**Comment by maoberlehner** [comment]
Sure – Previously there were two selectors:

```css
::-moz-selection {
  background: #b3d4fc;
  text-shadow: none;
}

::selection {
  background: #b3d4fc;
  text-shadow: none;
}
```

But because of the use of Autoprefixer, the vendor prefixed selector was removed. The comment explained, that the vendor prefixed and the regular selector could not be combined like

```css
/* This does not work */
::-moz-selection,
::selection {
  background: #b3d4fc;
  text-shadow: none;
}
```

But because there is just the non vendor prefixed selector in the src file, this comment is confusing.

BUT: In the autoprefixed dist file, the comment makes still sense, because there are both selectors beneath each other again. So I'm not quite sure if it's better to have a confusing comment in the src file, which makes sense in the dist file – or if we can remove the comment completely – or if it's worth the hassle to add the comment somehow in the build process and have it removed in the src file?
