### ISSUE TITLE
Font file address error at build time

### ISSUE THREAD

**Issue by NimaKaviyani** [h5bp/html5-boilerplate#2993]
### Prerequisites

- [x] I have [searched](https://github.com/h5bp/html5-boilerplate/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/h5bp/html5-boilerplate/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hello
The font file addresses are wrong at build time. The problem is in the `google-fonts.scss` file on `lines 40-43`. Please check these lines and correct the addresses.

![boilerplate](https://github.com/h5bp/html5-boilerplate/assets/32512803/af5ad8d5-2801-4320-b391-51b24cadb534)

### Reduced test cases

```SCSS
@mixin googleFont($font) {
  $fontFamily: map-get($font, "name");
  $folderName: map-get($font, "folder");
  $fileName: map-get($font, "files");
  $weights: map-get($font, "weights");
  @each $weight in $weights {
    $weightName: map-get($fontWeightNames, $weight);
    @font-face {
      font-family: "#{$fontFamily}";
      font-weight: $weight;
      font-display: swap;
      src: url("../../fonts/#{$folderName}/#{$fileName}-#{$weightName}.eot"); /* IE 9 - 11 */
      src: url("../../fonts/#{$folderName}/#{$fileName}-#{$weightName}.eot?#iefix") format('embedded-opentype'), /* IE 9 - 11 */
      url("../../fonts/#{$folderName}/#{$fileName}-#{$weightName}.woff2") format('woff2'),
      url("../../fonts/#{$folderName}/#{$fileName}-#{$weightName}.woff") format('woff');
    }
  }
}
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of HTML% Boilerplate are you using?

v1.0.1
