### ISSUE TITLE
Update Supported Node Versions

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#3236]
### Prerequisites

- [x] I have [searched](https://github.com/h5bp/html5-boilerplate/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [x] I have read the [contributing guidelines](https://github.com/h5bp/html5-boilerplate/blob/main/.github/CONTRIBUTING.md)

### Proposal

- Our test workflows are currently setup for Node 18x and 20x (https://github.com/h5bp/html5-boilerplate/blob/main/.github/workflows/test.yml)
- Node v18 is EOL as of April 30, 2025
- Node v24 is a bit late but should be available soon (next week?)
- We should update Node versions tested to be 20, 22, 24 (that's Maintenance, LTS and Current) 

Related; we should combine the `test-windows` and `test` workflows.. we can have it test on Windows, macOS and Ubuntu all in the same workflow. Something like this:

```yml
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
          - 22
          - 24
        os: [ubuntu-latest, macos-latest, windows-latest]
```

### Motivation and context

To support currently supported versions of NodeJS
