### ISSUE TITLE
using font-size unit 'rem'

### ISSUE THREAD

**Issue by remitbri** [h5bp/html5-boilerplate#517]
What about using rem unit for font-size ? (read http://snook.ca/archives/html_and_css/font-size-with-rem )
We would need to change the line #61 in css/style.css from

``` css
body { font:13px/1.231 sans-serif; *font-size:small; } /* Hack retained to preserve specificity */
```

to

``` css
html{ font:62.5%/1.231 sans-serif; *font-size:small; } /* Hack retained to preserve specificity */
```

and after that, since the 'root' unit is 10px;

``` css
body{font-size: 13px; font-size:1.3rem}
div.foo{font-size: 20px; font-size:2rem;}
```
