### ISSUE TITLE
Unnecessary CSS Rule?

### ISSUE THREAD

**Issue by matzipan** [h5bp/html5-boilerplate#575]
``` css
html { overflow-y: scroll }
```

Why is it needed? It adds an unnecessary scroll in chrome when the content does not even exceed the length of the page.
