### ISSUE TITLE
hack text-decoration for links

### ISSUE THREAD

**Issue by milani** [h5bp/html5-boilerplate#690]
Using `text-decoration: underline` for anchors cause some issues specially for languages that have dots under some letters. there is a work-around for this:

``` css
a{
    border-bottom: 1px solid currentcolor;
}
```
