### ISSUE TITLE
Add auto hyphenation to typography CSS

### ISSUE THREAD

**Issue by ghost** [h5bp/html5-boilerplate#708]
With the new Firefox 6 release and Safari 5.1 we now have two major browsers supporting CSS3 hyphenation. So maybe it's a good idea to add hyphenation to the default boilerplate CSS to enable great typography in advanced browser.

``` css
p {
-webkit-hyphen: auto;
-moz-hyphen: auto;
hyphen: auto;
}
```

More info on hyphenation: http://blog.fontdeck.com/post/9037028497/hyphens
