### ISSUE TITLE
Safari 5.0.4: overflow-y: scroll (html) - scrollbar always visible

### ISSUE THREAD

**Issue by reinaris** [h5bp/html5-boilerplate#791]
``` css
html { font-size: 100%; overflow-y: scroll; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
```

Safari 5.0.4 always shows a vertical scrollbar because of the overflow-y: scroll. It drove me crazy in combination with Fancybox (because i thought it was a fancybox problem), but the content in the iframe I opened used the boilerplate (good work by the way).

Maybe fixable?
