### ISSUE TITLE
CSS selector works on HTML4 but not on Boilerplate

### ISSUE THREAD

**Issue by Axiol** [h5bp/html5-boilerplate#795]
Hello, I'm trying to migrate my blog to Boilerplate, but got a little CSS trouble :

I've got this structure (the short way :) )

``` html
<html>
    <body>
        <div id="container">
           <header>
               <a><h1>Axiol <span>&amp;</span> Me</h1></a>
           </header>
        </div>
    </body>
</html>
```

And this CSS

``` css
html body div#container header a:hover h1 span {
    -webkit-transform:rotate(360deg);
    -moz-transform:rotate(360deg);
    transform:rotate(360deg);
    -webkit-transition:all .5s ease-in;
    -moz-transition:all .5s ease-in;
    transition:all .5s ease-in;
}
```

It works perfectly on HTML4 pages but won't work on Boilerplate. Would anyone have a solution ?
