### ISSUE TITLE
Add the class .no-touch to all :hovers in style.css

### ISSUE THREAD

**Issue by vasilisvg** [h5bp/html5-boilerplate#802]
iOs triggers the mouseover event on the first touch when something changes. This happens even with simple changes like a new color or removal of an underline. The click-event only fires the second time you touch. 

This is easy to solve, if modernizr is included, by adding the class `.no-touch` to each `:hover` rule. In style.css there are two occurences of `a:hover`, one on line 19 and one on 21. They would look like this:

``` css
.no-touch a:hover { color: #06e; }
.no-touch a:hover, a:active { outline: 0; }
```
