### ISSUE TITLE
Question: why margin reset has been removed for headings?

### ISSUE THREAD

**Issue by paulmillr** [h5bp/html5-boilerplate#814]
Hey HTML5guys. Why this feature has been removed -- it was rarely used or something like that? I think, it's pretty useful -- different browsers use different margins etc.

``` css
h1, h2, h3, h4, h5, h6 { margin: 0; }
```
