### ISSUE TITLE
identifying an MQ parsing bug...

### ISSUE THREAD

**Issue by paulirish** [h5bp/html5-boilerplate#823]
I have a slight challenge that someone might be excited about...

Was reading http://dev.opera.com/articles/view/safe-media-queries/  and it got me excited.. turned out to be a bust but i was wondering...

Can you craft a media query that always succeeds in oldIE but is parsed as a media query everywhere else?

okay .. so an example that DOESNT work..

``` css
    div { background: red; }

@media screen` and (min-width: 600px)  {
    div { background: lime; }
}
```

Ideally, oldIE sees `@media screen`, sees that tilde, and interprets it as a comma (essentially) and ignores the rest of the line up to the `{` .. it then applies whats in the MQ block.
Meanwhile MQ-supporting browsers ignore the tilde and parse the MQ... only applying those styles in the case of min-width:600..

So.. can we brute force some testing on this to identify any MQ hack with this behavior?

Am i crazy?
## why?

because you could do "mobile-first" media queries with a single file. boom.

<hr>

@mathiasbynens this seems up your alley...
