### ISSUE TITLE
CSS formatting

### ISSUE THREAD

**Issue by sindresorhus** [h5bp/html5-boilerplate#930]
Any reason style.css is using one-liner rules?

IMO the CSS file should set a good example for developers on how to format their CSS file.

Isn't the last example a lot more readable and easily editable?

``` css
body { margin: 0; font-size: 1em; line-height: 1.4; }

body, button, input, select, textarea { font-family: sans-serif; color: #222; }
```

``` css
body {
    margin: 0;
    font-size: 1em;
    line-height: 1.4;
}

body,
button,
input,
select,
textarea {
    font-family: sans-serif;
    color: #222;
}
```
